### ISSUE TITLE
Rank grade images out of date

### ISSUE THREAD

**Issue by Adambean** [Dragaera/observatory#31]
The badge for squad leader (grade 3) is no longer yellow:
[https://observatory.morrolan.ch/images/skill_tier_badges/squad_leader.png](https://observatory.morrolan.ch/images/skill_tier_badges/squad_leader.png)
It is now an all white version of veteran (grade 4) and commandant (grade 5).

The badge for veteran (grade 4) no longer has a white top:
[https://observatory.morrolan.ch/images/skill_tier_badges/veteran.png](https://observatory.morrolan.ch/images/skill_tier_badges/veteran.png)
This is in fact what squad leader looks (grade 3) like now. Veteran should have a yellow top.

**Comment by Lavode** [comment]
Thanks for the heads-up, didn't realize they had already changed. I'll take a look at the images shipping with the current game client, one of these days. :)

**Comment by Adambean** [comment]
I'm sure the change just snuck in a few months ago. :) I only noticed when I saw the yellow one for squad leader and thought "oh wow that's retro".

**Comment by Adambean** [comment]
Thank you. :)

**Comment by Adambean** [comment]
Sorry to bring this up again, but it looks like build 327 with it's completely new set of icons has rather stomped on your toes there.

**Comment by Lavode** [comment]
@Adambean Yup, I noticed. Bad timing, I guess. :grin: 
The new icons have a colour gradient around the actual badge, which looks crappy on a white background. Will have to find a way to show those nicely - either by manually removing the gradient, or eg having a black circle as background for the badges.

Might take a while, bit busy. :)
