### ISSUE TITLE
Update the badge icons

### ISSUE THREAD

**Issue by Burrely** [Dragaera/observatory#38]
The badge icons on obs are outdated (pre unearthed update). Issueing updated badge icons on obs.

**Comment by Lavode** [comment]
Mind the gradient in the game-shipped badges. Looks crappy on white background, possible solutions:
- Strip colour gradient
- Add (black) circular background

**Comment by Lavode** [comment]
Merged to master in 6aa3fd7b1b18f0412bfb212efd5b26583187ac2d
