### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by sundarv85** [Dragaera/observatory#46]
Learning Resque and Rails and was trying your repo.

During the initial setup, I ran the docker and when I run 

```
bundle exec padrino s
```

I'm getting the error

```
sequel-5.23.0/lib/sequel/adapters/postgres.rb:152:in `async_exec': PG::UndefinedTable: ERROR:  relation "badges" does not exist (Sequel::DatabaseError)
LINE 1: SELECT * FROM "badges" LIMIT 1
```

What steps am I missing

**Comment by Lavode** [comment]
Huh, that's quite an interesting project to use to learn  resque & rails - how'd you stumble upon it, @sundarv85?

In either case - something like this should get you started, from a fresh clonse of the repository:

Start by copying over the required env files:
- `cp .env.development.dist .env.development`
- `cp .env.test.dist .env.dist`
- `cp .env.development.gorge.dist .env.development.gorge`

Then start the docker containers:
- `docker-compose up`

You'll now notice `gorge-application` (one of the involved services) spewing errors. Run its migrations to fix those:
- `docker-compose run gorge-application migrate`

Now run the migrations of Observatory:
- `bundle exec rake sq:migrate`

Now you should be able to start the development server:
- `bundle exec padrino s`

You'll then also want background workers & schedulers running:
- `QUEUE=* bundle exec rake resque:work`
- `bundle exec rake resque:scheduler`
